name: kelimanya
description: "A professional word puzzle game."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.2
  google_mobile_ads: ^5.1.0
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  shared_preferences: ^2.2.0
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  firebase_core_web: ^2.24.1
  firebase_auth_web: ^5.15.3
  cloud_firestore_web: ^4.4.12
  firebase_messaging_web: ^3.10.10
  google_sign_in_web: ^0.12.4+4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
